"""
ml/train_isolation_forest.py
------------------------------
Trains a REAL sklearn IsolationForest on sensor_readings already stored
in MongoDB (typically generated by the Phase 2 simulator, ideally via
ml/generate_training_data.py so a labeled eval set also exists).

Per the master plan's non-negotiable rules:
  - Real, trained, saved/loaded model - no hardcoded predictions.
  - Generic: features never depend on sensor_type (see
    ml/feature_engineering.py).
  - No data leakage: for each sensor, the model is trained only on the
    chronologically FIRST 80% of its readings; the last 20% (in time)
    are held out for evaluation and never used for fitting.

Reads directly from MongoDB with a synchronous pymongo client (this is
an offline batch job, not part of the request path, so it does not
need to go through Motor/async or the HTTP API - unlike the simulator,
which the master plan requires to write through the API, this script
only READS already-stored data for training).

Usage:
    python ml/train_isolation_forest.py
    python ml/train_isolation_forest.py --contamination 0.1
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import joblib
from pymongo import MongoClient
from sklearn.ensemble import IsolationForest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import settings  # noqa: E402
from ml.feature_engineering import FEATURE_NAMES, compute_feature_matrix  # noqa: E402

MODELS_DIR = Path(__file__).resolve().parent / "models"
MODEL_PATH = MODELS_DIR / "isolation_forest.joblib"
META_PATH = MODELS_DIR / "isolation_forest_meta.json"
LABELED_DATA_PATH = Path(__file__).resolve().parent / "datasets" / "labeled_readings.jsonl"

MIN_READINGS_REQUIRED = 30
TRAIN_FRACTION = 0.8


def _load_readings_by_sensor(db) -> dict[str, list[dict]]:
    """Load every reading, grouped by sensor_id, sorted chronologically."""
    sensors = {s["sensor_id"]: s for s in db.sensors.find({})}
    readings_by_sensor: dict[str, list[dict]] = defaultdict(list)

    cursor = db.sensor_readings.find({}).sort([("sensor_id", 1), ("timestamp", 1), ("_id", 1)])
    for doc in cursor:
        doc["id"] = str(doc["_id"])
        readings_by_sensor[doc["sensor_id"]].append(doc)

    return sensors, readings_by_sensor


def _load_labels() -> dict[str, str | None]:
    """Optional: id -> injected_fault (or None), from generate_training_data.py."""
    if not LABELED_DATA_PATH.exists():
        return {}
    labels: dict[str, str | None] = {}
    with LABELED_DATA_PATH.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            labels[row["id"]] = row["injected_fault"]
    return labels


def build_dataset(sensors: dict, readings_by_sensor: dict) -> tuple[list, list, list, list, list]:
    """
    Returns (train_X, eval_X, eval_ids, eval_values, eval_sensor_ids).
    Splits each sensor's readings chronologically: first 80% -> train,
    last 20% -> eval (held out, never trained on).
    """
    train_X: list[list[float]] = []
    eval_X: list[list[float]] = []
    eval_ids: list[str] = []
    eval_values: list[float] = []
    eval_sensor_ids: list[str] = []

    for sensor_id, readings in readings_by_sensor.items():
        sensor = sensors.get(sensor_id)
        if sensor is None or len(readings) < 2:
            continue

        values = [r["value"] for r in readings]
        features = compute_feature_matrix(sensor["normal_min"], sensor["normal_max"], values)

        split_idx = max(1, int(len(readings) * TRAIN_FRACTION))
        train_X.extend(features[:split_idx])

        for i in range(split_idx, len(readings)):
            eval_X.append(features[i])
            eval_ids.append(readings[i]["id"])
            eval_values.append(readings[i]["value"])
            eval_sensor_ids.append(sensor_id)

    return train_X, eval_X, eval_ids, eval_values, eval_sensor_ids


def evaluate_unsupervised(model: IsolationForest, eval_X: list[list[float]]) -> dict:
    if not eval_X:
        return {"n_eval": 0}
    preds = model.predict(eval_X)  # -1 = anomaly, 1 = normal
    n_anomalies = int((preds == -1).sum())
    return {
        "n_eval": len(eval_X),
        "n_flagged_anomalous": n_anomalies,
        "flagged_rate": round(n_anomalies / len(eval_X), 4),
    }


def evaluate_supervised(model: IsolationForest, eval_X, eval_ids, labels: dict) -> dict | None:
    """Real precision/recall/F1 against ground-truth injected_fault labels,
    when a labeled dataset from generate_training_data.py is available."""
    if not labels:
        return None

    y_true = []
    y_pred = []
    preds = model.predict(eval_X)
    for reading_id, pred in zip(eval_ids, preds):
        if reading_id not in labels:
            continue
        y_true.append(1 if labels[reading_id] is not None else 0)
        y_pred.append(1 if pred == -1 else 0)

    if not y_true:
        return None

    tp = sum(1 for t, p in zip(y_true, y_pred) if t == 1 and p == 1)
    fp = sum(1 for t, p in zip(y_true, y_pred) if t == 0 and p == 1)
    fn = sum(1 for t, p in zip(y_true, y_pred) if t == 1 and p == 0)
    tn = sum(1 for t, p in zip(y_true, y_pred) if t == 0 and p == 0)

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    return {
        "n_labeled_eval": len(y_true),
        "tp": tp, "fp": fp, "fn": fn, "tn": tn,
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--contamination", type=float, default=None,
                         help="Override contamination. Default: estimated from labeled "
                              "data if available, else sklearn's 'auto'.")
    parser.add_argument("--n-estimators", type=int, default=200)
    args = parser.parse_args()

    client = MongoClient(settings.mongodb_uri)
    db = client[settings.mongodb_db_name]

    sensors, readings_by_sensor = _load_readings_by_sensor(db)
    total_readings = sum(len(v) for v in readings_by_sensor.values())

    if total_readings < MIN_READINGS_REQUIRED:
        client.close()
        raise SystemExit(
            f"Only {total_readings} sensor_readings found (need >= {MIN_READINGS_REQUIRED}).\n"
            "Run the simulator first, e.g.:\n"
            "  python ml/generate_training_data.py --in-process --ticks 200 --fault-rate 0.15"
        )

    train_X, eval_X, eval_ids, eval_values, eval_sensor_ids = build_dataset(sensors, readings_by_sensor)
    client.close()

    if len(train_X) < MIN_READINGS_REQUIRED:
        raise SystemExit(
            f"Only {len(train_X)} training rows after the chronological split "
            f"(need >= {MIN_READINGS_REQUIRED}). Generate more data first."
        )

    labels = _load_labels()
    contamination = args.contamination
    if contamination is None:
        if labels:
            n_faulty = sum(1 for v in labels.values() if v is not None)
            contamination = max(0.01, min(0.5, n_faulty / len(labels))) if labels else "auto"
        else:
            contamination = "auto"

    model = IsolationForest(
        n_estimators=args.n_estimators,
        contamination=contamination,
        random_state=42,
    )
    model.fit(train_X)

    unsup = evaluate_unsupervised(model, eval_X)
    sup = evaluate_supervised(model, eval_X, eval_ids, labels)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, MODEL_PATH)

    meta = {
        "feature_names": FEATURE_NAMES,
        "n_estimators": args.n_estimators,
        "contamination": contamination,
        "n_train_samples": len(train_X),
        "n_sensors_trained_on": len(readings_by_sensor),
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "unsupervised_eval": unsup,
        "supervised_eval": sup,
    }
    META_PATH.write_text(json.dumps(meta, indent=2))

    print("Trained Isolation Forest fault detector.")
    print(f"  train samples: {len(train_X)}  (from {len(readings_by_sensor)} sensors)")
    print(f"  contamination: {contamination}")
    print(f"  unsupervised eval: {unsup}")
    print(f"  supervised eval:   {sup if sup else '(no labeled data - run generate_training_data.py for real precision/recall)'}")
    print(f"  saved model:  {MODEL_PATH}")
    print(f"  saved meta:   {META_PATH}")


if __name__ == "__main__":
    main()
